name: "publish"

on:
    push:
        branches:
            - release

jobs:
    publish-tauri:
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                include:
                    - platform: "windows-latest"
                      args: ""

        runs-on: ${{ matrix.settings.platform }}
        steps:
            - uses: actions/checkout@v4

            - name: setup node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*

            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable
              with:
              # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
                targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

            - name: Install pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 8
                  run_install: true

            - uses: tauri-apps/tauri-action@dev
              env:
                  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
                  TAURI_SIGNING_PRIVATE_KEY: "${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}"
                  TAURI_SIGNING_PUBLIC_KEY: "${{ secrets.TAURI_SIGNING_PUBLIC_KEY }}"
                  TAURI_SIGNING_PRIVATE_KEY_PASSWORD: "1234"
              #    DATABASE_URL: ${{ secrets.DATABASE_URL }}
              with:
                  tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
                  releaseName: "App v__VERSION__"
                  releaseBody: "See the assets to download this version and install."
                  releaseDraft: false
                  prerelease: false
                  includeUpdaterJson: true
                  args: ${{ matrix.settings.args }}
